# GIMP / GAP Videoinfo file
(onion_auto_enable yes) 
(onion_auto_replace_after_load no) 
(onion_auto_delete_before_save no) 
(onion_number_of_layers 1) 
(onion_ref_mode 0) 
(onion_ref_delta 0) 
(onion_ref_cycle no) 
(onion_stack_pos 0) 
(onion_stack_top no) 
(onion_opacity_initial 0) 
(onion_opacity_delta 0) 
(onion_ignore_botlayers 0) 
(onion_select_mode 0) 
(onion_select_casesensitive no) 
(onion_select_invert no) 
(onion_select_string  "") 
(onion_ascending_opacity no) 
